FROM python:3.6.0-slim

COPY requirements.txt \
     pre-requirements.txt \
     /tmp/

RUN set -ex \
  && buildDeps=' \
      postgresql-server-dev-all \
      build-essential \
      libssl-dev \
      libffi-dev \
      python-dev \
  ' \ 
  && apt-get update \
  && apt-get install -y ${buildDeps} --no-install-recommends \
  && pip3 install --no-cache-dir -r /tmp/pre-requirements.txt \
  && pip3 install --no-cache-dir -r /tmp/requirements.txt \
  && apt-get purge -y --auto-remove ${buildDeps}

