"""empty message

Revision ID: e0a63eae6e2a
Revises: b310b29ffa94
Create Date: 2017-03-08 01:59:28.160466

"""

# revision identifiers, used by Alembic.
revision = 'e0a63eae6e2a'
down_revision = 'b310b29ffa94'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_binaryes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('digit', sa.SmallInteger(), nullable=False),
    sa.Column('representation', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_binaryes')
    # ### end Alembic commands ###
